services:
  - type: web
    name: my-python-app
    env: python
    buildCommand: |
      apk add --no-cache portaudio-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
